package ExceptionHandling;

public class Exceptions {
	
	
public static int divide(int a, int b) throws divideByZeroException {	// here we are passing a checked exception to the calling function, in this caise main
	if(b == 0) {
		throw new divideByZeroException();  
			
//		throw new ArithmeticException();
	}
	return a/b;
}
	

	public static void main(String[] args) {
		// 3 types of exceptions in java: 
//		Errors: 
//		Checked: expected exceptions
//		Unchecked: Unexpected exceptions
		
		
		try {					// try/catch will deal with the exception, instead of letting it be passed up to main
			divide(10,0);
			
		} catch (divideByZeroException error) {
			
			System.out.println("Divide by 0 exception");
			//error.printStackTrace();   // un-commenting this will print the stack trace in red
		}
		
		System.out.println("Main");
	}

}
